### ISSUE TITLE
Refactor adapters

### ISSUE THREAD

**Issue by bojiang** [bentoml/BentoML#1002]
## Is your feature request related to a problem? Please describe.
- Allowed users to customize HTTP response/ AWS lambda event like headers, etc
- Made contribution of adapters easier.
- Drier adapter code
- A more handy CLI UX for user defined API function

## Describe the solution you'd like

- Introduce InferenceTask & InferenceResult types
- Move micro-batching related logic out of adapters

### For adapter developers
Now a basic JSON input adapter would be very simple:
```python

ApiFuncArgs = Tuple[Sequence[JsonSerializable],]

class JsonInput(BaseInputAdapter):
    def from_http_request(self, req: HTTPRequest) -> InferenceTask:
        return  InferenceTask(http_headers=r.parsed_headers, data=req.body)

    def from_aws_lambda_event(self, event: AwsLambdaEvent) -> InferenceTask:
        return InferenceTask(aws_lambda_event=event, data=event['body'].encode(JSON_CHARSET))

    def from_cli(self, cli_args: Sequence[str]) -> Iterator[InferenceTask]:
        for json_file in parse_cli_input(cli_args):
            yield InferenceTask(cli_args=cli_args, data=json_file.read())

    def extract_user_func_args(self, tasks: Sequence[InferenceTask]) -> ApiFuncArgs:
        json_inputs = []
        for task in tasks:
            try:
                json_str = task.data.decode(JSON_CHARSET)
                parsed_json = json.loads(json_str)
                json_inputs.append(parsed_json)
            except UnicodeDecodeError:
                task.discard(
                    http_status=400, err_msg=f"JSON must be encoded in {JSON_CHARSET}"
                )
            except json.JSONDecodeError:
                task.discard(http_status=400, err_msg="Not a valid JSON format")
            except Exception:  # pylint: disable=broad-except
                err = traceback.format_exc()
                task.discard(http_status=500, err_msg=f"Internal Server Error: {err}")
        return (json_inputs,)
```

And it allows user to query:

**by CLI**
```shell
bentoml run <yourservice>:latest --input {"height": 180, "weight": 80} {"height": 190, "weight": 100}
```

```shell
bentoml run <yourservice>:latest --input-file path/to/your/*.json --max-batch-size 10
```

**by HTTP**
```shell
curl -i \
    --header "Content-Type: application/json" \
    --request POST \
    --data '{"height": 190, "weight": 100}' \
    localhost:5000/predict
```

### For Users
Users could customize HTTP headers, AWS lambda events and CLI exit code by return instances of InferenceResult in their API function:

```python
import bentoml
from bentoml.types import InferenceResult, InferenceContext

class MyService(bentoml.BentoService):
    @bentoml.api(input=JsonInput())
    def predict(self, json_obj_list, contexts=contexts):
        rv = []
        predictions = user_model.run(json_obj_list)
        for context, prediction in zip(contexts, predictions):
            if context.http_headers['Accept'] == "application/json":
                rv.append(
                    InferenceResult(
                        data=prediction,
                        http_status=200,
                        http_headers={"Content-Type": "application/json"},
                        aws_lambda_event={"data": prediction},
                        cli_status=0,
                ))
        return rv
```

## TODO
decision:
- [ ] enable BATCH_MODE_SUPPORTED for all adapters; enable batching server by default?
- [x] ~~merge FileInput & MultiFileInput and so on?~~
- [x] ~~remove legacy adapters?~~

cli:
- [x] multiple cli input
- [ ] better cli error message (now just print err_msg)
- [ ] system cli args encoding?

adapters:
- [x] prototype json input adapter
- [x] annotated_image_input
- [x] file input adapter and its tests
- [x] dataframe input adapter and its tests
- [x] image input adapter and its tests
- [x] tensorflow tensor adapter and its tests
- [x] other input adapters and their tests
- [x] other output adapters

chore:
- [ ] apply `set_dependencies`
- [ ] benchmark
- [ ] test clipper handler
- [ ] 2e2 tests
