### ISSUE TITLE
Better TensorFlow integration

### ISSUE THREAD

**Issue by bojiang** [bentoml/BentoML#1188]
**Describe the bug**

When I tried to serve a tensorflow model, I encountered the following problems:
1. I use the keras API (tensorflow.keras) officially recommended by TensorFlow 2.0 to build my model. Which artifact should I use? #1186
2. When I try to use KerasModelArtifact, I get error #1185
3. When I try to use TensorflowSavedModelArtifact, I first get an error: `'_UserObject' object has no attribute'predict'` #1169
4. When I call `model(input_data)` directly, the above problem is solved, but a new problem appears: #1016
5. In the end, I explicitly converted the type according to the TensorSpec of the model, and finally it ran successfully.

**Additional context**
There are four different API set for TensorFlow:
1. [TensorFlow 1.x] Estimator
1.  [TensorFlow 1.x] raw TensorFlow API with Session (Static computational graphs)
1. [TensorFlow 1.14, 2.x] tensorflow.keras (Recommended in official Docs)
1. [TensorFlow 1.x 2.x] raw TensorFlow API (Eager Execution) [eg](https://colab.research.google.com/drive/15QZMSIrvE4MgVq2GnQ0XUsqQssY6sn7w#scrollTo=8T1Pf4mbuVRI&forceEdit=true&sandboxMode=true)

There are serveral ways to save/load models:
1. `tf.keras.models.load_model`
1. `tf.saved_model.load`
1. `tf.compat.v1.xxx`

**TODOs**
- [ ] Find out the behavior of each API set
- [ ] Provide an instruction about the differences between two artifacts and how to choose between them
- [ ] Modify artifacts to fit the behavior of original models as much as possible

**Environment:**
 - Python Version [e.g. Python 3.6.9]
 - BentoML Version [e.g. BentoML-0.9.2]

**Comment by bojiang** [comment]
also: #1200

**Comment by EricPreventa** [comment]
Any update or resolution on this?

**Comment by parano** [comment]
@EricPreventa I believe @bojiang is working on a patch for this and it should be out for review later this week
