### ISSUE TITLE
BentoML Configuration Redesign

### ISSUE THREAD

**Issue by ssheng** [bentoml/BentoML#1374]
### Background
BentoML introduced a configuration system in the early days to simplify user customizations and scale developer productivity. The design starts with an out-of-box configuration that just works. For advanced users who need additional customizations, configuration can be overridden with user supplied values. A number of pain points summarized below have been encountered by our developers and users with the current design. We want to take this opportunity to redesign the configuration system and scale BentoML for the next five years.
#### Too Many Ways to Override
There are too many ways to override the same configuration key making it difficult for users and developers to establish a clear mental model.
- CLI explicit parameters
- CLI config settings ($ bentoml config set key=value)
- Environment variables
- Configuration file override
#### Convoluted Override Precedence
Keys defined in the bentoml.cfg already have a well established override precedence. However, the override precedence between CLI parameters and BentoML configurations still rely on application logic to define, particularly for configuration keys prefixed with “default”.
#### All-or-Nothing Override
Users must provide a full bentoml.cfg configuration file even if they wish to override only a handful of keys. Due to the same limitation, BentoML config CLI copies the entire default configuration to the BentoML home directory when the user sets a single configuration key. Once a copy of bentoml.cfg is placed, evolving the default configuration becomes impossible unless the user manually deletes the bentoml.cfg file.
#### Lack of Configuration Scope
Overridden configurations apply to all subsequent BentoML CLI commands, users may not wish to apply the same configuration to two different commands.
#### Configuration Coupling with Implementation
Implementation classes all have to import and be aware of the configuration module, making unit testing and code modularization challenging.
#### Lack of Hierarchy and Data Types
The current “.ini” format of the configuration file does not easily allow configuration key hierarchy and collection data types, such as list and dict.
### Goals
1. Default configurations should continue to work for most of the use cases
2. Deterministic precedence order of configuration override
3. Allow partial overrides through any means
4. Limit configuration override to only the current session (no persistence)
5. Decouple configuration with implementation classes
6. Introduce hierarchy and collection data types
7. Backward compatible with the current configuration system
### Design
Started a design draft. Comments are welcome. https://docs.google.com/document/d/1kriInVhjCEoXblh_hBBRwFfi6VwgzwFogQ2tyDoRa5U/edit#heading=h.l0i6f5osh4wr

### Pull Requests
- [x] Introduce Dependency Injection and Configuration Revamp (https://github.com/bentoml/BentoML/pull/1422)
- [x] Make dependency inject happen during initialization (#1595)
- [x] Migrated Packages to the new Configuration
  - [x] server (https://github.com/bentoml/BentoML/pull/1422)
  - [x] marshal (https://github.com/bentoml/BentoML/pull/1422)
  - [x] yatai (#1595)
  - [x] service (#1595)
- [ ] Refactor existing use of cerberus to schema (Deferred to #1505)
- [x] Refactor and remove all existing use cases of legacy config (#1595)
- [x] Re-structure configuration format (#1595)

**Comment by mayurnewase** [comment]
Draft doesn't seem to be public,could you please give necessary permissions?

**Comment by ssheng** [comment]
Is there a group I can give commenting permission to?

**Comment by ssheng** [comment]
Tracking option should be moved out of config and into CLI parameters.

**Comment by ssheng** [comment]
Should logging configuration be a part of the new bentoml.yml or remained on its own in logging.yml.

**Comment by harshitsinghai77** [comment]
This is merged. This issue should be closed?

**Comment by ssheng** [comment]
@harshitsinghai77 The new configuration system is still not public yet. We are targeting release 0.13 to make this the new standard of configuration for BentoML. There are still some remaining work to do (see the pull request checklist).
